### ISSUE TITLE
Пример работы с TradesStream

### ISSUE THREAD

**Issue by decadence** [metaseller/tinkoff-invest-api-v2-php#12]
Здравствуйте. Спасибо за библиотеку.

А есть где-то пример работы с TradesStream для получения информации о совершенных сделках? По аналогии с MarketDataStream, как в примере в README.

**Comment by metaseller** [comment]
Здравствуйте, нет примера к сожалению, но поидее там несложно переделать пример по образу и подобию

**Comment by decadence** [comment]
Да что-то пока не получилось :( В общем, буду благодарен, если у вас найдётся какой-то минимальный рабочий пример. Заодно можно будет его в документацию добавить.
