### ISSUE TITLE
Как работает этот API?

### ISSUE THREAD

**Issue by YAMER1** [metaseller/tinkoff-invest-api-v2-php#2]
Здравствуйте, подскажите, пожалуйста, чайнику. Возникли проблемы при установке, установка работает только при указании версии php и ссылок на расширения /usr/local/bin/php7.4 -d extension=/home/a/userbeget/.beget/tmp/grpc-1.46.3/.libs/grpc.so .local/bin/composer  require metaseller/tinkoff-invest-api-v2-ph возможно, что команды по такому же принципу, не проверил. Этот Api только для того, чтобы работать в консоли с командами и загрузкой php или всё же при правильной настройке страницы examples могут октрываться в браузере и проблема с хостингом?

**Comment by metaseller** [comment]
Привет, там же в Readme описано, какие зависимости и пакеты нужны. grpc.so нужно прописать в php.ini для php / cli. 

Свое приложение вы можете сделать хоть консольным, хоть "браузерным". Примеры будут открываться и так и так, но для простоты, чтобы не настраивать веб-сервис, я запускал их как консольные.
