### ISSUE TITLE
Вывести все акции с фильтром.

### ISSUE THREAD

**Issue by YAMER1** [metaseller/tinkoff-invest-api-v2-php#3]
Здравствуйте, как я понял, example5 выводит все акции со всеми их стаканами. Проблема в том, что эта страница зависает и выдаёт ошибку 502 gateway, зависает весь сайт. Я удалил вторую часть кода, где "Создаем подписку на данные", пытаюсь вывести только акции. Теперь мне выдаёт ошибку Allowed memory size, недостаточно памяти. Думаю, что это связано с тем, что акций больше тысячи у Тинькофф. Напишите, пожалуйста, как можно ограничить список выводимых акций? 
Я пробовал править файл Tinkoff/Invest/V1/Share.php, там поставил $short_enabled_flag = true, $buy_available_flag = true, $sell_available_flag = true,  $api_trade_available_flag = true. Вроде бы все флаги, которые должны ограничивать список выводимых акций, но это не помогает. Я правильно понял, что Share.php это что-то вроде файла с настройками? Как ещё можно ограничить выводимые акции? К примеру ограничения по стране, только Россия, Америка или по объёму торгов, есть такое?

**Comment by YAMER1** [comment]
Или в Тинькофф API ты либо получаешь всех акции, либо не получаешь ни одной? Очень нужно ограничение по объёму, чтобы отсеять всякую ерунду.

**Comment by metaseller** [comment]
см. https://github.com/metaseller/tinkoff-invest-api-v2-php/blob/main/src/providers/InstrumentsProvider.php#L115

**Comment by YAMER1** [comment]
Спасибо, но как я уже писал, мне нужен список всех акций, а не одной. Я думал, что этот API в этом поможет, но пока сомневаюсь. Мне надо сначала вывести все акции с их текущими ценами, их данными. Как можно вывести все акции, которые доступны для покупки?

**Comment by YAMER1** [comment]
И поясните, пожалуйста, FB это значит Face Book? Я погуглил, но сразу не понял, что это значит.
