### ISSUE TITLE
Как вывести список всех акций с их ценами?

### ISSUE THREAD

**Issue by YAMER1** [metaseller/tinkoff-invest-api-v2-php#4]
Здравствуйте, напишите, пожалуйста, как вывести все акции с их ценами? Я ранее спрашивал, но не ответили.

**Comment by metaseller** [comment]
Здравствуйте, не понятен вопрос, что вы понимаете под ценой? 

Все акции вы можете получить, используя модель провайдера инструментов или прямой запрос к АПИ через соответствующий клиент.

А цена - вы можете взять последние свечи, можете взять стакан (но это работает только пока идут торги), можете использовать метод получения последней цены. GetLastPrice

Вы что под ценой акции понимаете?

**Comment by metaseller** [comment]
Запросите все shares и у вас будут и id и figi и ticker инструментов

Я могу сделать пример, но не в ближайшее время, к сожалению

**Comment by YAMER1** [comment]
Хорошо, спасибо. Интересно, какая будет нагрузка на сайт в таком случае, сколько оперативной памяти нужно. Я не спешу, попробую сделать самостоятельно, но пример также не помешает в будущем.
