### ISSUE TITLE
Error occurred during parsing: Unexpected wire type

### ISSUE THREAD

**Issue by YAMER1** [metaseller/tinkoff-invest-api-v2-php#5]
Здравствуйте, хотел попробовать вывести список всех акций, но теперь появилась ошибка. Ошибка при создании экземпляра класса new GetInfoRequest() и new PortfolioRequest() и InstrumentsProvider::create; Раньше работало и выводило портфель, теперь ничего не работает. Я 2 недели не занимался этим, а сейчас появилась ошибка, которой раньше не было. Может быть в tinkoff api что-то изменилось или как решить?

[Google\Protobuf\Internal\GPBDecodeException] 
Error occurred during parsing: Unexpected wire type. (0)
/tinkoff/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:355

**Comment by metaseller** [comment]
Обновил протофайлы, попробуйте обновиться до версии 0.3.6 (https://github.com/metaseller/tinkoff-invest-api-v2-php/releases/tag/0.3.6), если не поможет - попробуйте обновить зависимость google/protobuf через composer update

PS Извиняюсь, сейчас не имею возможности отвечать оперативно
