### ISSUE TITLE
Вы живы?

### ISSUE THREAD

**Issue by YAMER1** [metaseller/tinkoff-invest-api-v2-php#6]
Здравствуйте, уже скоро будет месяц с момента моего последнего вопроса. Я понимаю, что тут всё добровольно, но всё же, как можно исправить ошибку "Error occurred during parsing: Unexpected wire type"? Если нужно больше информации, то могу предоставить.

**Comment by metaseller** [comment]
Не стоит дублировать issues, сейчас отвечу в соседней
