### ISSUE TITLE
Добавить поддержку id инструмента в запрос на создание заявки

### ISSUE THREAD

**Issue by kikimarik** [metaseller/tinkoff-invest-api-v2-php#9]
Сейчас есть некоторое расхождение с описанием модели запроса [PostOrderRequest](https://tinkoff.github.io/investAPI/orders/#postorderrequest) сервиса ордеров.

В описании значится, что поле `figi` устарело (не гарантируется его неизменяемость) и рекомендуют использовать `instrument_id`, однако в SDK пока нет возможности задействовать это поле.

**Comment by metaseller** [comment]
Здравствуйте, сейчас попробую пересобрать модели.

**Comment by metaseller** [comment]
@kikimarik Пересобрал модели из обновленных контрактов, добавил поддержку Instrument UID в InstrumentsProvider. 

Обновите библиотеку до версии 0.4.5, должны появиться нужные методы и атрибуты.

**Comment by kikimarik** [comment]
Спасибо, обновился
